export const T = {
    TIMER_ADD_HISTORY: "TIMER_ADD_HISTORY",
    TIMER_SECONDS: "TIMER_SECONDS",
    TIMER_MINUTES: "TIMER_MINUTES",
    TIMES_HOURS: "TIMES_HOURS",
    TIMERS_CLEAR_DISPLAY: "TIMERS_CLEAR_DISPLAY",
    TIMERS_START : 'TIMERS_START',
    TIMES_DELETE_ELEMENT : 'TIMES_DELETE_ELEMENT',
  };